export const SELECT_PAYMENT_METHOD = 'APP/PAYMENTS/SELECT_PAYMENT_METHOD';
export const EDIT_PAYMENT_METHOD = 'APP/PAYMENTS/EDIT_PAYMENT_METHOD';
export const REMOVE_PAYMENT_METHOD = 'APP/PAYMENTS/REMOVE_PAYMENT_METHOD';
export const RESET_PAYMENT_METHOD = 'APP/PAYMENTS/RESET_PAYMENT_METHOD';
export const ADD_PAYMENT_METHOD = 'APP/PAYMENTS/ADD_PAYMENT_METHOD';

