export const ADD_CART_ITEM = 'APP/CART/ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'APP/CART/REMOVE_CART_ITEM';
export const CLEAR_CART = 'APP/CART/CLEAR_CART';
export const PLACE_ORDER = 'APP/CART/PLACE_ORDER';